### ISSUE TITLE
India_Compliance Causing issue 'Invalid "depends_on" expression on many module;

### ISSUE THREAD

**Issue by QuakeString** [resilient-tech/india-compliance#978] opened 2023-08-18 10:11 UTC
### Information about bug

1. l've taken backup(db/privte-files/public-files/site-config) of my site from prvious installatin which was as normal installation.
Then erpnext was Production Branch Version - 14.26 or so ( not remember exactly).
Now I've install erpnext on docker (Production branch version-14) as per official guide. and restore my previous site. also The India_Compliance Version-14
after all done, I get a lot of issue. my invoice form is not displaying. can't edit the address or items
![2023-08-17_23-44](https://github.com/resilient-tech/india-compliance/assets/5375918/fcc9ea33-6fe4-4686-ad97-59f2d81c3a74)
![2023-08-17_23-43_1](https://github.com/resilient-tech/india-compliance/assets/5375918/b6237d7d-33d1-4de3-87c2-9049c6e7f429)
![2023-08-17_23-43](https://github.com/resilient-tech/india-compliance/assets/5375918/83165c3f-0958-4d04-924d-e68a0d6c4229)
2. After lot of tri and research I uninstall India_compliance app, and then check, 
3. I found that all error are not and I can see my inoivce form or edit the address or items.

### Version

```
erpnext 14.34.3
frappe 14.44.0
hrms 14.10.0
india_compliance 14.15.1
payments 0.0.1
whitelabel 0.0.1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ljain112** [comment] 2023-08-18 10:34
Hello,

Can you please share the traceback to further investigate the issue?
Traceback is important and crucial to help resolve the bug.
https://stackoverflow.com/questions/36503244/how-to-copy-a-stack-trace-from-the-chrome-console

**Comment by vorasmit** [comment] 2023-08-18 10:43
Do you have custom files exported in your custom app whitelabel 0.0.1?
Probably these custom fields in India Compliance App are being overwritten because of this.

**Comment by QuakeString** [comment] 2023-08-18 10:44
> Do you have custom files exported in your custom app whitelabel 0.0.1? Probably these custom fields in India Compliance App are being overwritten because of this.

No, Whitelabel is not not installed on my site which has issue.

**Comment by QuakeString** [comment] 2023-08-18 10:46
> 

Here is console output of page where Invoice Form not showing
![2023-08-18_16-13_1](https://github.com/resilient-tech/india-compliance/assets/5375918/f16031d4-f421-4fad-9577-49424275c2ee)

This one the popups `Invalid "depends_on" expression`
![2023-08-18_16-13](https://github.com/resilient-tech/india-compliance/assets/5375918/37e15561-8f13-454a-9034-b439b7656c0e)

**Comment by vorasmit** [comment] 2023-08-18 10:53
This seems to issue with the Installation and/or customisation of the app that you have.
We recommend you use Frappe Cloud and it would simplify your Installation.

**Comment by shreyasubale** [comment] 2023-08-21 08:03
i am also facing a exact same issue. This is a new install , and no other packages are present.I used easy_install prod version to install erpnext, then i installed india_compliance via this command 
 docker compose -f frappe-compose.yml exec backend bench get-app --branch version-14 https://github.com/resilient-tech/india-compliance.git and docker compose -f frappe-compose.yml exec backend bench install-app india_compliance

**Comment by vorasmit** [comment] 2023-08-23 09:56
I guess the issue is in how you are installing the application. Not sure about Docker and the correctness of your installation steps.
Doesn't seem to be an issue the app itself and hence closing this issue.

**Closed as not planned by vorasmit** 2023-08-23 09:56 UTC
Labels: question

**Comment by shreyasubale** [comment] 2023-08-24 15:35
@vorasmit  as mentioned in the official document, docker is the recommended way to install erpnext in production. Does india_compliance suggest another way ? I think we should support official ways to install right ?

**Comment by vorasmit** [comment] 2023-08-25 04:28
I never said we don't support Docker Installation. Frappe Cloud is using docker. I meant that I cannot vouch for the steps that you mentioned for installation.

You shouldn't be facing this issue if you are installing this correctly.

If you can replicate this issue of Frappe Cloud, please share the link to the site and we will fix this.

**Comment by QuakeString** [comment] 2023-10-08 02:26
Found a clue/fix for `invalid "depends on" expression`
these express on Custom Field "Item-gst_hsn_code" of "Item" doctype 
![2023-10-08_06-54](https://github.com/resilient-tech/india-compliance/assets/5375918/2f97dc6f-e63f-4377-a419-9b1e459a7768)

but the issue of totally blank invoice form view is still persist. I'm sure its not something issue of installation.
![2023-10-08_07-55](https://github.com/resilient-tech/india-compliance/assets/5375918/4d2133dd-a5d4-40ae-8dee-591aa72079f7)

**Comment by vorasmit** [comment] 2023-10-08 02:38
Seems JS build issue. Try `bench build` in the bench directory.

**Comment by QuakeString** [comment] 2023-10-08 02:48
getting this error 
![2023-10-08_08-14](https://github.com/resilient-tech/india-compliance/assets/5375918/6a18a20f-fdbd-4e55-b72e-8ce8750e7d14)
and this is the site.
![2023-10-08_08-23](https://github.com/resilient-tech/india-compliance/assets/5375918/ba2c2992-3356-46a0-98be-c1f465596477)
