### ISSUE TITLE
Enable Automatically Add Taxes and Charges from Item Tax Template

### ISSUE THREAD

**Issue by IBSLPUNE** [resilient-tech/india-compliance#443] opened 2023-01-08 15:13 UTC
Url : https://bitscontrolandsolutions.frappe.cloud/

![image](https://user-images.githubusercontent.com/31270467/211204072-598e8084-f8a1-4719-adda-62a13539e0f7.png)

Thanks & Regards
Devid Patel
+91 9377833133

**Comment by IBSLPUNE** [comment] 2023-01-13 05:58
Any update

**Comment by vorasmit** [comment] 2023-01-13 06:18
Hello Devid,

By design, the item tax template (for India) is used just for fetching correct tax rates (it can include all GST accounts).
Tax account is chosen from Sales Taxes and Charges Template and Purchase Taxes and Charges Template.

**Sample Item Tax Template looks like this. (As generated by default)**

![image](https://user-images.githubusercontent.com/10496564/212249804-334d20d5-c713-40cc-baba-91e41fa967f9.png)

- If this option (as you have requested) is allowed, it would fetch all tax accounts (incorrect).
- Problems would also occur if you have items with different tax rates in a transaction.

Hence, it's disabled and not supposed to be used.

---

PS: This can be a good [discuss topic](https://discuss.frappe.io/c/erpnext/india-compliance/), instead of a GitHub issue.

**Comment by sagarvora** [comment] 2023-01-22 11:07
I am closing this issue, since I don't see further activity here. Please feel free to comment here if you think this needs further attention.

**Closed as not planned by sagarvora** 2023-01-22 11:07 UTC
