### ISSUE TITLE
Place of Supply Error- Purchase Order

### ISSUE THREAD

**Issue by RJMHASKE** [resilient-tech/india-compliance#621] opened 2023-04-21 11:06 UTC
### Information about bug

After update India compliance app on latest version, below error comes while creating PO

<img width="731" alt="image" src="https://user-images.githubusercontent.com/119041865/233620713-8ba244be-acc6-4e91-ac59-aab34b3527d9.png">

### Version

ERPNext: v14.22.2 (HEAD)
Frappe Framework: v14.33.1 (HEAD)
India Compliance: v14.5.4 (HEAD)
Payments: v0.0.1 (HEAD)

### Relevant log output / Stack trace / Full Error Message.

```shell
aceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 26, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 305, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 327, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 259, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1045, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 914, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1248, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/india_compliance/india_compliance/gst_india/overrides/transaction.py", line 719, in validate_transaction
    validate_place_of_supply(doc)
  File "apps/india_compliance/india_compliance/gst_india/overrides/transaction.py", line 356, in validate_place_of_supply
    valid_options = doc.meta.get_field("place_of_supply").options.split("\n")
AttributeError: 'NoneType' object has no attribute 'split'

(anonymous) @ request.js:457
/api/method/frappe.desk.form.save.savedocs:1     Failed to load resource: the server responded with a status of 500 ()
request.js:457 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 26, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 305, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 327, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 259, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1045, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 914, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1248, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/india_compliance/india_compliance/gst_india/overrides/transaction.py", line 719, in validate_transaction
    validate_place_of_supply(doc)
  File "apps/india_compliance/india_compliance/gst_india/overrides/transaction.py", line 356, in validate_place_of_supply
    valid_options = doc.meta.get_field("place_of_supply").options.split("\n")
AttributeError: 'NoneType' object has no attribute 'split'

(anonymous) @ request.js:457
DevTools failed to load source map: Could not load content for webpack://Quill/node_modules/quill-delta/dist/Delta.js.map: Fetch through target failed: Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for webpack://Quill/node_modules/quill-delta/dist/AttributeMap.js.map: Fetch through target failed: Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for webpack://Quill/node_modules/quill-delta/dist/Op.js.map: Fetch through target failed: Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for webpack://Quill/node_modules/quill-delta/dist/Iterator.js.map: Fetch through target failed: Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
jquery.js:10109     POST https://testerp.parason.com/api/method/frappe.desk.form.save.savedocs 500
send @ jquery.js:10109
ajax @ jquery.js:9690
frappe.request.call @ request.js:268
frappe.call @ request.js:105
u @ save.js:242
n @ save.js:23
frappe.ui.form.save @ save.js:269
(anonymous) @ form.js:807
Promise.then (async)
(anonymous) @ dom.js:262
frappe.run_serially @ dom.js:260
validate_and_save @ form.js:798
(anonymous) @ form.js:737
save @ form.js:734
Save @ toolbar.js:652
(anonymous) @ page.js:268
dispatch @ jquery.js:5430
c1.handle @ jquery.js:5234
request.js:457 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 26, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 305, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 327, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 259, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1045, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 914, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1248, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/india_compliance/india_compliance/gst_india/overrides/transaction.py", line 719, in validate_transaction
    validate_place_of_supply(doc)
  File "apps/india_compliance/india_compliance/gst_india/overrides/transaction.py", line 356, in validate_place_of_supply
    valid_options = doc.meta.get_field("place_of_supply").options.split("\n")
AttributeError: 'NoneType' object has no attribute 'split'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RJMHASKE** [comment] 2023-04-21 11:09
Address details
<img width="546" alt="image" src="https://user-images.githubusercontent.com/119041865/233621570-9a6ec444-1c2e-477d-93fa-db8632a9de4d.png">

**Comment by RJMHASKE** [comment] 2023-04-21 12:44
Place of Supply Options not set in purchase order
<img width="857" alt="image" src="https://user-images.githubusercontent.com/119041865/233639281-2e133c2e-dd8e-4f29-8608-fb26b236228b.png">

**Comment by DaizyModi** [comment] 2023-04-21 13:15
I am not able to replicate the Issue. Seems options are available.

![image](https://user-images.githubusercontent.com/54097382/233645054-d9980cf4-7176-4c39-8093-6da821994356.png)

**Comment by vorasmit** [comment] 2023-04-21 13:20
Hi,

Can you check if options are correctly set for Purchase Invoice?

Mostly patch is not run correctly and `bench migrate` should resolve this for you.

**Comment by RJMHASKE** [comment] 2023-04-21 14:17
In Purchase Invoice Place of Supply options are set but in Purchase Order options are not set (field type data)

**Comment by RJMHASKE** [comment] 2023-04-21 14:17
Site is hosted on Frappe Cloud

**Comment by sagarvora** [comment] 2023-04-21 14:21
duplicate of #612 

@RJMHASKE can you try "migrate" action or upgrading to the latest release once?

**Comment by RJMHASKE** [comment] 2023-04-21 14:23
> Place of Supply Options not set in purchase order <img alt="image" width="857" src="https://user-images.githubusercontent.com/119041865/233639281-2e133c2e-dd8e-4f29-8608-fb26b236228b.png">

please see this PO options are not set

**Comment by BaaridunNasr** [comment] 2023-04-23 08:08
@RJMHASKE 
I had to manually add new fields as per the spec in the app. 

If you need an immediate but dirty workaround, it works. Of course, this may have some unintended consequences depending on any other apps you install.

**Comment by sagarvora** [comment] 2023-04-24 10:07
Is this happening with the latest release as well? `v14.6.0`? Please let me know if that's the case, I will reopen it.

**Closed as completed** 2023-04-24 10:07 UTC
