### ISSUE TITLE
Invalid Data Format in sandbox env

### ISSUE THREAD

**Issue by bhavesh95863** [resilient-tech/india-compliance#650] opened 2023-05-07 13:45 UTC
Hey,

I am trying to test get party information in the sandbox env with provided GST number but getting following error

![image](https://user-images.githubusercontent.com/34086262/236681206-012a5e9d-70f2-41e4-a792-4450af5dfe50.png)

**Comment by sagarvora** [comment] 2023-05-07 22:26
Hi @bhavesh95863,

This is a duplicate of https://github.com/resilient-tech/india-compliance/issues/595.

**Closed as not planned by sagarvora** 2023-05-07 22:26 UTC
