### ISSUE TITLE
Error While Processed to Payment 

### ISSUE THREAD

**Issue by riddhisolanki001** [resilient-tech/india-compliance#547] opened 2023-04-03 09:45 UTC
Showing Error regarding API call while Click on Precessed to Payment Button

Current behavior
when the user clicks the button processed to payment system shows the error that " requests. exceptions.HTTPError: 400 Client Error: Bad Request for URL: "

![Screenshot from 2023-04-03 15-02-39](https://user-images.githubusercontent.com/105703644/229473766-d0685182-60af-4129-8f92-d24891cca74b.png)

**Comment by sagarvora** [comment] 2023-04-03 09:47
Duplicate of https://github.com/resilient-tech/india-compliance/issues/542, please continue discussion there.

**Closed as not planned by sagarvora** 2023-04-03 09:47 UTC
