### ISSUE TITLE
e-Invoice Log missing values invoice_data, signed_invoice and signed_qr_code.

### ISSUE THREAD

**Issue by patil-ruturaj** [resilient-tech/india-compliance#617] opened 2023-04-21 07:55 UTC
### Information about bug

On Sales Invoice submission, an e-Invoice log was created in the system but values missing in the e-Invoice Log.
IRN QR code not printing on Invoice print because signed_qr_code filed is empty in e-Invoice Log.
![image](https://user-images.githubusercontent.com/124342766/233574089-ea11fcec-d398-45c7-8386-089ed27fac99.png)

While Printing e-Invoice print from Sales Invoice
The system is showing """ Invoice Data is not available in the e-Invoice Log linked to this invoice. """ msg in the print.
![image](https://user-images.githubusercontent.com/124342766/233575104-1595d059-e395-4cf5-b489-29c2c515e2ee.png)

### Version

Frappe Version - v14.31.0
ERPNext Version - v14.20.3
India Compliance Version - v14.5.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment] 2023-04-21 13:40
Usually, this happens when you are trying to re-generate the e-Invoice for the same invoice number after 2 days.
e-Invoice data is not available with govt after 2 days. You may check the Ack Date for your reference. Also, you can track this in Integration Request Log.

Still, we make sure and create an e-Invoce log with available information.

Hope this helps. Closing this as its not a bug.

**Closed as not planned by vorasmit** 2023-04-21 13:40 UTC
Labels: bug
