### ISSUE TITLE
While Create Sales Order Nonetype AttributeError

### ISSUE THREAD

**Issue by barathprathosh** [resilient-tech/india-compliance#624] opened 2023-04-23 09:48 UTC
### Information about bug

After update the India Compliance App, i raise the Sales Order and while click on save it pop-up the Arttribute Error. And i Check the Place of supply option and customer address it proper only (Customer Address place of supply = West Bengal).

![Screenshot from 2023-04-23 15-08-26](https://user-images.githubusercontent.com/48587404/233832318-177a5f5b-e503-4868-91cd-8dd1a92bac02.png)

### Version

Ecommerce Integrations: v1.15.4 (main)
ERPNext: v14.22.2 (version-14)
Frappe Framework: v14.33.1 (version-14)
India Compliance: v14.6.0 (version-14)
Payments: v0.0.1 (develop)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DaizyModi** [comment] 2023-04-24 05:43
Check if options are set in `place_of_supply` field of sales order. Check this once - https://github.com/resilient-tech/india-compliance/issues/621#issuecomment-1517910403

**Comment by sagarvora** [comment] 2023-04-24 10:09
This is duplicate of https://github.com/resilient-tech/india-compliance/issues/621 and https://github.com/resilient-tech/india-compliance/issues/612. Please review comments there, and respond there if necessary.

**Closed as completed by sagarvora** 2023-04-24 10:09 UTC
