### ISSUE TITLE
build failed while get-app

### ISSUE THREAD

**Issue by Shankarv19bcr** [resilient-tech/india-compliance#369] opened 2022-12-02 12:57 UTC
![image](https://user-images.githubusercontent.com/95605398/205297891-a4fe9936-4641-4995-8afe-7115c6ed5ce7.png)

**Comment by sagarvora** [comment] 2022-12-02 14:44
It seems like you're using an incompatible version of Frappe. What's the output of `bench version`?

**Comment by sagarvora** [comment] 2022-12-02 15:16
Closing, not a bug. If you're still stuck with this issue, consider emailing support at the following email:
```
hello at indiacompliance dot app
```

**Closed as not planned by sagarvora** 2022-12-02 15:16 UTC
